name: GoodNews
favicon: null
layout_spectrum: 0.3060725175309926
typography_spectrum: 0.47309198416769505
title: "Thoughts and short texts based on Bible, the God's word."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7796377919148654
  lightness: 0.905364166945219
  saturation: 0.6701435518916696
  rhythmicContrast: 0.7921049792785197
purpose: []
